version: '3.8'

services:
  scraper-worker:
    build: .
    env_file:
      - .env
    shm_size: '2gb'
    volumes:
      - ./instagram_cookies.json:/app/instagram_cookies.json
    restart: unless-stopped
    command: /app/startup.sh